version: "3"
services:
  mongo-database:
    image: mongo:4
    container_name: "mongo-database"
    ports:
      - 27017:27017
   
  api:
    image: everjava/springbootmongo:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    links:
      - mongo-database